
// if 6 is valid, go to 6
IF
	Global(%var_buff%,"LOCALS",242)	// did Player5
	!InPartySlot(Myself,5)		// am not Player6
	See(Player6)				// can see Player6
	Range(Player6,6)			// Player6 not too far away
THEN
	RESPONSE #100
		SetGlobal(%var_buff%,"LOCALS",250)	// goto Player6
END

// 6 isnt valid
IF
	Global(%var_buff%,"LOCALS",242)	// did Player5
THEN
	RESPONSE #100
		SetGlobal(%var_buff%,"LOCALS",0)
		DisplayStringHead(Myself,@186)	// ~Buffing done~
END

